<?php

namespace ContainerYYE7BCk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E45DIvtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e45DIvt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e45DIvt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'offreRepository' => ['privates', 'App\\Repository\\OffreRepository', 'getOffreRepositoryService', true],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
        ], [
            'offreRepository' => 'App\\Repository\\OffreRepository',
            'translator' => '?',
        ]);
    }
}
