<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQcSRFyt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQcSRFyt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQcSRFyt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQcSRFyt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQcSRFyt\App_KernelDevDebugContainer([
    'container.build_hash' => 'QcSRFyt',
    'container.build_id' => '3e30020b',
    'container.build_time' => 1743615002,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQcSRFyt');
